requires "Command::Runner";
requires "YAML::Tiny";
requires "Path::Tiny";
requires "File::chdir";
requires "Types::Path::Tiny";
requires "Applify";
requires "Moo";
requires "namespace::autoclean";
requires "Modern::Perl";
