requires "Command::Runner";
requires "YAML::Tiny";
requires "Path::Tiny";
requires "File::chdir";
requires "URL::Encode";
requires "Text::MicroTemplate::DataSection";
requires "Types::Path::Tiny";
requires "Applify";
requires "Moo";
requires "namespace::autoclean";
requires "Modern::Perl";
requires "URI";
requires "Parallel::ForkManager";
requires "Type::Tiny", ">=1.008004";
