#!/usr/bin/env perl

use Modern::Perl;
use Applify;
use CI::Repo;

version 0.01;
documentation __FILE__;

subcommand repo => 'Repo management' => sub {
    option bool => sync_upstream => "Sync upstream repos";
    option str => items => "Path to reactive layer ", required => 1, n_of => 1;
};

sub command_repo {
    my ( $app, $action ) = @_;
    my $repo = CI::Repo->new(
        items => $app->{items},
    );
    $action =~ tr/-/_/;
    $repo->$action if $repo->can($action);
    return 0;
}

app {
    my $self = shift;
    return 0;
};

__END__

=head1 NAME

monk - CLI for CI

=head1 SYNOPSIS

    # Sync upstream git repos
    $ monk repo --sync-upstream --layer-list my-layers.yaml --charm-list my-charms.yaml

=head1 AUTHOR

Adam Stokes - c<adamjs@cpan.org>

=cut
