#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/lib";

use Modern::Perl;
use Moo;
use MooX::Commander;
use namespace::autoclean;

my $commander = MooX::Commander->new(
    base_class=> 'CI'
    );
$commander->dispatch(argv => \@ARGV);


__END__

=encoding utf8

=head1 NAME

monk - CLI for CI

=head1 SYNOPSIS

    # Sync upstream git repos
    $ monk repo --items my-layers.yaml --items my-charms.yaml forks

=head1 SUBCOMMANDS

Each subcommand takes the form of:

    $ monk <subcommand> <action>

=head2 repo

Git repo management

    $ monk repo --help

=head3 ACTIONS

=over 4

=item sync

Sync the upstream repositories

    $ monk repo sync --items ancillary-list.yaml

=back

=head1 COPYRIGHT

Copyright (c) 2020, Adam Stokes

=head1 LICENSE

Perl.

=head1 AUTHOR

Adam Stokes - c<adamjs@cpan.org>

=cut
